baseURL = 'https://lorenzomodolo.com/'
languageCode = 'en-us'
title = "Lorenzo"

enableRobotsTXT = true


defaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "ðŸ‡ºðŸ‡¸"
    weight = 1
  [languages.br]
    languageName = "ðŸ‡§ðŸ‡·"
    weight = 2



[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 1

[services]
  [services.googleAnalytics]
    id = 'G-D74E9WRELM'

