baseURL = 'https://lorenzomodolo.com/'
languageCode = 'en-us'
title = "Lorenzo"

enableRobotsTXT = true


defaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "ğŸ‡ºğŸ‡¸"
    weight = 1
  [languages.br]
    languageName = "ğŸ‡§ğŸ‡·"
    weight = 2